/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as RecrutamentoRouteImport } from './routes/recrutamento'
import { Route as ProjetosRouteImport } from './routes/projetos'
import { Route as JenewsRouteImport } from './routes/jenews'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as EmpresasRouteImport } from './routes/empresas'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicoSlugRouteImport } from './routes/servico.$slug'
import { Route as EstruturaSlugRouteImport } from './routes/estrutura.$slug'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const RecrutamentoRoute = RecrutamentoRouteImport.update({
  id: '/recrutamento',
  path: '/recrutamento',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosRoute = ProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const JenewsRoute = JenewsRouteImport.update({
  id: '/jenews',
  path: '/jenews',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasRoute = EmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicoSlugRoute = ServicoSlugRouteImport.update({
  id: '/servico/$slug',
  path: '/servico/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EstruturaSlugRoute = EstruturaSlugRouteImport.update({
  id: '/estrutura/$slug',
  path: '/estrutura/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/empresas': typeof EmpresasRoute
  '/faqs': typeof FaqsRoute
  '/jenews': typeof JenewsRoute
  '/projetos': typeof ProjetosRoute
  '/recrutamento': typeof RecrutamentoRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/estrutura/$slug': typeof EstruturaSlugRoute
  '/servico/$slug': typeof ServicoSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/empresas': typeof EmpresasRoute
  '/faqs': typeof FaqsRoute
  '/jenews': typeof JenewsRoute
  '/projetos': typeof ProjetosRoute
  '/recrutamento': typeof RecrutamentoRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/estrutura/$slug': typeof EstruturaSlugRoute
  '/servico/$slug': typeof ServicoSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/empresas': typeof EmpresasRoute
  '/faqs': typeof FaqsRoute
  '/jenews': typeof JenewsRoute
  '/projetos': typeof ProjetosRoute
  '/recrutamento': typeof RecrutamentoRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/estrutura/$slug': typeof EstruturaSlugRoute
  '/servico/$slug': typeof ServicoSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacto'
    | '/empresas'
    | '/faqs'
    | '/jenews'
    | '/projetos'
    | '/recrutamento'
    | '/servicos'
    | '/sobre'
    | '/estrutura/$slug'
    | '/servico/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacto'
    | '/empresas'
    | '/faqs'
    | '/jenews'
    | '/projetos'
    | '/recrutamento'
    | '/servicos'
    | '/sobre'
    | '/estrutura/$slug'
    | '/servico/$slug'
  id:
    | '__root__'
    | '/'
    | '/contacto'
    | '/empresas'
    | '/faqs'
    | '/jenews'
    | '/projetos'
    | '/recrutamento'
    | '/servicos'
    | '/sobre'
    | '/estrutura/$slug'
    | '/servico/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactoRoute: typeof ContactoRoute
  EmpresasRoute: typeof EmpresasRoute
  FaqsRoute: typeof FaqsRoute
  JenewsRoute: typeof JenewsRoute
  ProjetosRoute: typeof ProjetosRoute
  RecrutamentoRoute: typeof RecrutamentoRoute
  ServicosRoute: typeof ServicosRoute
  SobreRoute: typeof SobreRoute
  EstruturaSlugRoute: typeof EstruturaSlugRoute
  ServicoSlugRoute: typeof ServicoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recrutamento': {
      id: '/recrutamento'
      path: '/recrutamento'
      fullPath: '/recrutamento'
      preLoaderRoute: typeof RecrutamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jenews': {
      id: '/jenews'
      path: '/jenews'
      fullPath: '/jenews'
      preLoaderRoute: typeof JenewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas': {
      id: '/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof EmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servico/$slug': {
      id: '/servico/$slug'
      path: '/servico/$slug'
      fullPath: '/servico/$slug'
      preLoaderRoute: typeof ServicoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estrutura/$slug': {
      id: '/estrutura/$slug'
      path: '/estrutura/$slug'
      fullPath: '/estrutura/$slug'
      preLoaderRoute: typeof EstruturaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactoRoute: ContactoRoute,
  EmpresasRoute: EmpresasRoute,
  FaqsRoute: FaqsRoute,
  JenewsRoute: JenewsRoute,
  ProjetosRoute: ProjetosRoute,
  RecrutamentoRoute: RecrutamentoRoute,
  ServicosRoute: ServicosRoute,
  SobreRoute: SobreRoute,
  EstruturaSlugRoute: EstruturaSlugRoute,
  ServicoSlugRoute: ServicoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
